version: '3.4'
services:
  mysql-##deployName##:
    image: 'mariadb'
    volumes:
      - '##baseFolder##/##deployName##/mysql:/var/lib/mysql'
    secrets:
      - wp_db_password
      - root_db_password
    environment:
      - MYSQL_USER=wp
      - MYSQL_DATABASE=wp
      - MYSQL_PASSWORD_FILE=/run/secrets/wp_db_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/root_db_password
    networks:
      - ##deployName##
    deploy:
      placement:
          constraints: [node.role == manager]
      replicas: 1
      restart_policy:
        condition: on-failure
  
  wp-##deployName##:
    image: 'wordpress:latest'
    volumes:
      - '##baseFolder##/##deployName##/wp-content:/var/www/html/wp-content'
    configs:
      - source: "php-vars"
        target: "/usr/local/etc/php/conf.d/vars.ini"
    secrets:
      - wp_db_password
    networks:
      - ##deployName##
      - ##publicNetwork##
    deploy:
      placement:
          constraints: [node.role == manager]
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.##deployName##.rule=Host(##hostRules##)
        - traefik.http.routers.##deployName##.entrypoints=web
        - traefik.http.services.##deployName##.loadbalancer.server.port=80
        - traefik.http.routers.##deployName##.middlewares=wordpress1-redirectscheme@docker
        - traefik.http.routers.##deployName##-secured.rule=Host(##hostRules##)
        - traefik.http.routers.##deployName##-secured.entrypoints=web-secured
        - traefik.http.routers.##deployName##-secured.tls.certresolver=mytlschallenge
    depends_on:
      - ##deployName##
    environment:
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wp_db_password
      WORDPRESS_DB_HOST: mysql-##deployName##
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_HOME', '##hostURL##' );
        define( 'WP_SITEURL', '##hostURL##' );
        define( 'FS_METHOD', 'direct' );
secrets:
  wp_db_password:
    external: true
  root_db_password:
    external: true
configs:
  php-vars:
    external: true
networks:
  ##deployName##:
    attachable: true
  ##publicNetwork##:
    external: true 
